### ISSUE TITLE
[FEATURE] Balance the Resources section (footer)

### ISSUE THREAD

**Issue by vinzvinci** [web3community/web3community.github.io#67]
### Detailed description

![image](https://user-images.githubusercontent.com/73097560/135774018-7b32db54-15c9-446d-b53a-bef8def855fd.png)

### Context

Add space to this resources section, put it in the center

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pattimcletchie** [comment]
@vinzvinci I would like to try and tackle this.

**Comment by vinzvinci** [comment]
Sure @pattimcletchie!

Feel free to write them down if you have a question

**Comment by pattimcletchie** [comment]
As I was working on this I noticed that on mobile everything is displayed inline for the links. 

I would imagine each link would be `display: block` so that they each get their own line... do you want me to fix that as well while I am in here? Or should I create an issue?

<img width="351" alt="Screen Shot 2021-10-04 at 8 26 10 PM" src="https://user-images.githubusercontent.com/12242330/135946082-17321132-b580-4e57-a5bb-9011065feb73.png">

**Comment by vinzvinci** [comment]
Yes, please fix that too @pattimcletchie

**Comment by Panquesito7** [comment]
> As I was working on this I noticed that on mobile everything is displayed inline for the links.
> 
> I would imagine each link would be `display: block` so that they each get their own line... do you want me to fix that as well while I am in here? Or should I create an issue?
> 
> <img alt="Screen Shot 2021-10-04 at 8 26 10 PM" width="351" src="https://user-images.githubusercontent.com/12242330/135946082-17321132-b580-4e57-a5bb-9011065feb73.png">

Create another issue for that, so we can discuss about it and see if that would work. 🙂
